### ISSUE TITLE
Connect Front-End to Back-End using ethers library

### ISSUE THREAD

**Issue by CptAstro** [UniversityDAO/udao#23]
- [x] Javascript -> Solidity. Figure out how to forward data from frontend to Solidity. This includes CID from IPFS, possibly a MetaMask wallet address, and more as needed. When somebody submits a proposal/grant or votes, we need to invoke Solidity function calls that run their logic.
- [x] Solidity -> Javascript. Figure out how to retrieve CID, yesVotes, noVotes, and active status from Solidity. This data is needed to populate all the fields present on our site.

**Comment by jagger-harris** [comment]
Added Javascript -> Solidity functions and merged into a new branch

**Comment by victor-wei126** [comment]
Closing since this should be addressed and done by #54, which should be merged asap.
