### ISSUE TITLE
Refresh Issue

### ISSUE THREAD

**Issue by CptAstro** [UniversityDAO/udao#49]
Right now, as of the reading dataflow rework, we only load all the data onto the page ONCE and that's as soon as a user presses "Launch App" on the landing page. Once they do so, it directs them to a "Loading" page where we then fetch all the data. Once the data is fetched and done loading, we automatically redirect to the dashboard page.

The problem with this is what if we're on the dashboard/grants/proposals pages, and the user refreshes the page, the page ends up being empty. It's empty because once the page refreshes the entire app has to re-render, and once it re-renders the user will be left on whatever page they refreshed on, meaning they essentially 'bypassed' the launch app button. This is a bit of an issue.

One solution would be to have an event listener for page refresh, and upon refresh we redirect them to the loading page. where data will be loaded up. The issue with this solution is that if somebody is on the grants page and refreshes, once the data loads back in they're going to be on the dashboard page. Not an app-breaking problem but still annoying from a user standpoint.

**Comment by victor-wei126** [comment]
Fixing this issue will probably also fix much of the react state management issue
