### ISSUE TITLE
IPFS shenanigans

### ISSUE THREAD

**Issue by jagger-harris** [UniversityDAO/udao#8]
IPFS implementation and other

- [ ] Connect IPFS to wallet
- [x] Upload files to IPFS
- [x] Determine to use host or use Web3 Storage
- [x] Javascript (how to display IPFS text and images using hash)
- [x] Create dummy form and upload text from form to IPFS

**Comment by CptAstro** [comment]
With PR #22, these issues should all be resolved :)

**Comment by jagger-harris** [comment]
#22 resolves this issue
